In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('pizza_sales.csv')
df.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,01-01-2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,01-01-2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,01-01-2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,01-01-2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,01-01-2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

In [2]:
df.isnull().sum()

pizza_id             0
order_id             0
pizza_name_id        0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
dtype: int64

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_name_id      48620 non-null  str
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  str
 5   order_time         48620 non-null  str
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  str
 9   pizza_category     48620 non-null  str
 10  pizza_ingredients  48620 non-null  str
 11  pizza_name         48620 non-null  str
dtypes: float64(2), int64(3), str(7)
memory usage: 4.5 MB

In [4]:
df.describe()

           pizza_id      order_id      quantity    unit_price   total_price
count  48620.000000  48620.000000  48620.000000  48620.000000  48620.000000
mean   24310.500000  10701.479761      1.019622     16.494132     16.821474
std    14035.529381   6180.119770      0.143077      3.621789      4.437398
min        1.000000      1.000000      1.000000      9.750000      9.750000
25%    12155.750000   5337.000000      1.000000     12.750000     12.750000
50%    24310.500000  10682.500000      1.000000     16.500000     16.500000
75%    36465.250000  16100.000000      1.000000     20.250000     20.500000
max    48620.000000  21350.000000      4.000000     35.950000     83.000000

In [6]:
df.duplicated().sum()

np.int64(0)

In [14]:
# Covert into date format
df['order_date']=pd.to_datetime(df['order_date'],format="%d-%m-%Y")
df['order_date'].tail(5)

48615   2015-12-31
48616   2015-12-31
48617   2015-12-31
48618   2015-12-31
48619   2015-12-31
Name: order_date, dtype: datetime64[us]

In [15]:
df['order_time']=pd.to_datetime(df['order_time'],format="%H:%M:%S").dt.time

In [38]:
#extract new column
df['day_of_week']=df['order_date'].dt.day_name()
df['day_of_week']

df['month']=df['order_date'].dt.month_name()
df['month']

df['hours_of_day']=pd.to_datetime(df['order_time'],format="%H:%M:%S").dt.hour
df['hours_of_day']

0        11
1        11
2        11
3        11
4        11
         ..
48615    21
48616    21
48617    21
48618    22
48619    23
Name: hours_of_day, Length: 48620, dtype: int32

In [35]:
#df=df.drop('day_of_week',axis=1)
df.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,day_name,month,hours_of_day
0,1,1,hawaiian_m,1,2015-01-01,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza,Thursday,January,11
1,2,2,classic_dlx_m,1,2015-01-01,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza,Thursday,January,11
2,3,2,five_cheese_l,1,2015-01-01,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza,Thursday,January,11
3,4,2,ital_supr_l,1,2015-01-01,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza,Thursday,January,11
4,5,2,mexicana_m,1,2015-01-01,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,Thursday,January,11

In [36]:

df['week'] = df['order_date'].dt.to_period('W').apply(lambda r: r.start_time)

# Weekly summary report
weekly_report = df.groupby('week').agg(
    total_revenue=('total_price', 'sum'),
    total_orders=('order_id', 'nunique'),   # unique orders, not rows
    total_quantity=('quantity', 'sum'),
    avg_order_value=('total_price', 'mean')
).reset_index()

print(weekly_report)

         week  total_revenue  total_orders  total_quantity  avg_order_value
0  2014-12-29        9863.60           254             591        16.976936
1  2015-01-05       15999.05           427             972        16.823396
2  2015-01-12       15115.95           400             917        16.832906
3  2015-01-19       15652.80           415             968        16.442017
4  2015-01-26       16351.10           436             975        16.996985
5  2015-02-02       16175.70           422             988        16.641667
6  2015-02-09       16085.55           423             976        16.755781
7  2015-02-16       15345.90           393             933        16.789825
8  2015-02-23       15961.80           409             972        16.678997
9  2015-03-02       16564.45           420             996        17.059166
10 2015-03-09       15820.55           404             965        16.759057
11 2015-03-16       15712.25           416             949        16.786592
12 2015-03-23       15689.25           427             954        16.619968
13 2015-03-30       16951.65           433            1025        16.934715
14 2015-04-06       16160.85           408             968        17.029347
15 2015-04-13       16088.50           414             967        16.899685
16 2015-04-20       16128.00           437             975        16.923400
17 2015-04-27       15224.25           423             934        16.584150
18 2015-05-04       16250.20           399             985        16.874559
19 2015-05-11       17139.70           458            1046        16.689094
20 2015-05-18       15908.40           414             953        17.179698
21 2015-05-25       15300.05           390             924        16.831738
22 2015-06-01       16650.20           423             997        16.938149
23 2015-06-08       15883.90           418             962        17.061117
24 2015-06-15       15394.75           410             920        16.991998
25 2015-06-22       16216.80           416             980        16.874922
26 2015-06-29       17509.50           474            1066        16.707538
27 2015-07-06       15888.70           417             950        17.047961
28 2015-07-13       16258.25           420             981        16.882918
29 2015-07-20       16351.65           433             985        17.086364
30 2015-07-27       14985.05           419             926        16.558066
31 2015-08-03       15611.95           426             955        16.643870
32 2015-08-10       16277.60           435             994        16.592864
33 2015-08-17       15676.85           407             959        16.713060
34 2015-08-24       14279.80           394             866        16.760329
35 2015-08-31       15542.75           397             945        16.694683
36 2015-09-07       16717.00           435            1009        16.817907
37 2015-09-14       15979.85           423             974        16.767943
38 2015-09-21       11026.40           288             674        16.757447
39 2015-09-28       16815.55           433            1008        17.054310
40 2015-10-05       13023.20           334             794        16.804129
41 2015-10-12       15482.70           386             933        16.995280
42 2015-10-19       14425.75           352             876        16.735209
43 2015-10-26       13262.45           371             810        16.703338
44 2015-11-02       16122.70           394             970        16.794479
45 2015-11-09       15448.30           400             944        16.737053
46 2015-11-16       14860.55           392             908        16.734854
47 2015-11-23       19753.90           491            1186        17.043917
48 2015-11-30       16613.80           424            1013        16.680522
49 2015-12-07       15667.50           417             959        16.632166
50 2015-12-14       15971.00           430             962        16.811579
51 2015-12-21       11427.85           298             693        16.805662
52 2015-12-28        7244.25           171             442        17.125887

In [39]:
from sqlalchemy import create_engine

username="postgres"
password="nitin123"
host="localhost"
port="5432"
database="pizza_sales_db"# database name you created in sql

engine=create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name="pizza_sales"
df.to_sql(table_name,engine,if_exists="replace",index=False)
print(f"Data Successfully Loaded into table '{table_name}'in database'{database}'.")

Data Successfully Loaded into table 'pizza_sales'in database'pizza_sales_db'.